import { StyleSheet } from "react-native";
import { GOLD, GOLD_DIM, GOLD_GLOW, BOX_SIZE } from "./colors";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#000" },
  center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28 },
  container: { padding: 24, alignItems: "center", gap: 16, paddingBottom: 40 },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,215,0,0.2)"
  },
  headerSide: { width: 72 },
  headerTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  headerTitle: { fontSize: 18, fontWeight: "700", color: GOLD, textAlign: "center" },
  backBtn: { fontSize: 17, color: GOLD, fontWeight: "600" },
  accountBtn: {
    alignSelf: "flex-end",
    backgroundColor: GOLD_DIM,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: GOLD,
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    ...GOLD_GLOW,
  },
  accountBtnText: { fontSize: 20 },

  // Home
  homeContainer: { padding: 24, gap: 16, paddingBottom: 40 },
  homeGreeting: { fontSize: 22, fontWeight: "700", color: GOLD, marginBottom: 4 },
  card: {
    backgroundColor: "#0f0f0f",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.4)",
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    ...GOLD_GLOW,
  },
  cardIcon: { fontSize: 36 },
  cardText: { flex: 1 },
  cardLabel: { fontSize: 20, fontWeight: "700", color: GOLD },
  cardDesc: { fontSize: 14, color: "rgba(255,215,0,0.6)", marginTop: 2 },
  cardArrow: { fontSize: 28, color: "rgba(255,215,0,0.4)", fontWeight: "300" },

  // Scan choice
  scanChoiceContainer: {
    flexGrow: 1,
    alignItems: "center",
    padding: 24,
    paddingTop: 44,
    paddingBottom: 40,
  },
  scanChoiceOptions: {
    width: "100%",
    maxWidth: 440,
    gap: 16,
    marginTop: 32,
  },
  scanChoiceCard: {
    backgroundColor: "#0f0f0f",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.4)",
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    ...GOLD_GLOW,
  },
  scanChoiceIcon: {
    width: 42,
    fontSize: 32,
    color: GOLD,
    fontWeight: "800",
    textAlign: "center",
  },
  uploadPreviewCard: {
    backgroundColor: "#0f0f0f",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.3)",
    padding: 16,
    gap: 12,
  },
  uploadPreviewFrame: {
    height: 220,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.25)",
    backgroundColor: "#050505",
    overflow: "hidden",
  },
  uploadPreviewImage: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  uploadPreviewActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  uploadPreviewAction: {
    flexBasis: 150,
    flexGrow: 1,
    flexShrink: 0,
    paddingVertical: 12,
  },
  secondaryBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  secondaryBtnText: {
    color: "rgba(255,215,0,0.8)",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },
  previewScanBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: 23,
    backgroundColor: GOLD,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    ...GOLD_GLOW,
  },
  previewScanBtnText: {
    color: "#000",
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },

  // Scanner
  scannerOuter: { flex: 1, alignItems: "center", justifyContent: "center", gap: 28 },
  scannerBoxWrapper: {
    borderRadius: 12,
    ...GOLD_GLOW,
  },
  scannerBox: {
    width: BOX_SIZE,
    height: BOX_SIZE,
    borderRadius: 12,
    overflow: "hidden",
  },
  corner: {
    position: "absolute",
    width: 36,
    height: 36,
    borderColor: GOLD,
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 8,
  },
  cornerTL: { top: 0, left: 0, borderTopWidth: 3, borderLeftWidth: 3 },
  cornerTR: { top: 0, right: 0, borderTopWidth: 3, borderRightWidth: 3 },
  cornerBL: { bottom: 0, left: 0, borderBottomWidth: 3, borderLeftWidth: 3 },
  cornerBR: { bottom: 0, right: 0, borderBottomWidth: 3, borderRightWidth: 3 },
  scanLineSolid: {
    height: 3,
    backgroundColor: GOLD,
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 8,
  },
  scanHint: { fontSize: 15, color: "rgba(255,215,0,0.8)", fontWeight: "600", textAlign: "center" },
  scanSubHint: { fontSize: 13, color: "rgba(255,255,255,0.7)", textAlign: "center", lineHeight: 20, maxWidth: 300, marginTop: -8 },
  captureIndicator: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 3,
    borderColor: "rgba(255,215,0,0.25)",
    backgroundColor: "rgba(255,215,0,0.08)",
    alignItems: "center",
    justifyContent: "center",
    ...GOLD_GLOW,
  },
  captureIndicatorDisabled: {
    opacity: 0.4,
  },
  captureIndicatorDot: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: GOLD,
  },

  // Loading / error
  loadingStep: { marginTop: 20, fontSize: 16, color: GOLD, fontWeight: "600", textAlign: "center" },
  errorIcon: { fontSize: 60, marginBottom: 8 },
  errorBody: { fontSize: 14, color: "rgba(255,255,255,0.6)", textAlign: "center", marginHorizontal: 24, marginTop: 6, lineHeight: 20 },
  errorTipBox: { marginTop: 18, marginHorizontal: 24, backgroundColor: "rgba(255,215,0,0.07)", borderWidth: 1, borderColor: "rgba(255,215,0,0.2)", borderRadius: 10, padding: 14, width: "90%" },
  errorTipLabel: { fontSize: 11, fontWeight: "800", color: GOLD, letterSpacing: 0.8, marginBottom: 4 },
  errorTipText: { fontSize: 13, color: "rgba(255,255,255,0.75)", lineHeight: 18 },

  // Result
  resultContainer: { padding: 20, alignItems: "center", gap: 16, paddingBottom: 40 },
  resultCoinName: { fontSize: 22, fontWeight: "800", color: GOLD, textAlign: "center" },
  resultCard: {
    width: "100%", backgroundColor: "#0f0f0f",
    borderRadius: 16, borderWidth: 1, borderColor: "rgba(255,215,0,0.3)",
    padding: 16, gap: 10,
  },
  resultCardTitle: { fontSize: 13, fontWeight: "700", color: "rgba(255,215,0,0.5)", letterSpacing: 1, textTransform: "uppercase" },
  resultRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  resultLabel: { fontSize: 14, color: "rgba(255,215,0,0.6)" },
  resultValue: { fontSize: 14, fontWeight: "700", color: GOLD, flexShrink: 1, textAlign: "right", marginLeft: 8 },
  resultSummary: { fontSize: 15, color: "rgba(255,215,0,0.85)", lineHeight: 22 },
  altRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  altInfo: { flex: 1, gap: 4 },
  altCoin: { fontSize: 13, color: "rgba(255,215,0,0.8)", fontWeight: "600" },
  altBarTrack: { height: 5, backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 3, overflow: "hidden" },
  altBarFill: { height: "100%", backgroundColor: "rgba(255,215,0,0.4)", borderRadius: 3 },
  altPct: { fontSize: 13, fontWeight: "700", color: "rgba(255,215,0,0.6)", width: 38, textAlign: "right" },
  unidentifiableTips: { width: "100%", backgroundColor: "#0f0f0f", borderRadius: 16, borderWidth: 1, borderColor: "rgba(255,215,0,0.2)", padding: 16, gap: 8, marginTop: 20, marginBottom: 4 },
  tipsTitle: { fontSize: 13, fontWeight: "700", color: "rgba(255,215,0,0.5)", letterSpacing: 1, textTransform: "uppercase", marginBottom: 4 },
  tipItem: { fontSize: 14, color: "rgba(255,215,0,0.75)", lineHeight: 22 },
  errorCard: { borderColor: "rgba(255,107,53,0.5)", backgroundColor: "rgba(255,107,53,0.06)" },
  errorRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  errorBullet: { color: "#FF6B35", fontSize: 16, lineHeight: 22 },
  errorText: { flex: 1, color: "#FF6B35", fontSize: 14, lineHeight: 22, fontWeight: "600" },
  valueRangeRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 12, marginVertical: 10 },
  valueBox: { alignItems: "center", backgroundColor: "rgba(255,215,0,0.08)", borderRadius: 10, borderWidth: 1, borderColor: "rgba(255,215,0,0.25)", paddingHorizontal: 20, paddingVertical: 10 },
  valueBoxLabel: { fontSize: 11, color: "rgba(255,215,0,0.5)", fontWeight: "600", letterSpacing: 1, textTransform: "uppercase" },
  valueBoxAmount: { fontSize: 24, fontWeight: "800", color: GOLD, marginTop: 2 },
  valueDash: { fontSize: 20, color: "rgba(255,215,0,0.4)", fontWeight: "300" },
  meterRow: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 6 },
  meterTrack: { flex: 1, height: 10, backgroundColor: "rgba(255,255,255,0.1)", borderRadius: 5, overflow: "hidden" },
  meterFill: { height: "100%", borderRadius: 5 },
  meterPct: { fontSize: 15, fontWeight: "700", width: 42, textAlign: "right" },
  meterLabel: { fontSize: 12, fontWeight: "600", marginTop: 4, letterSpacing: 0.5 },

  // Recently scanned
  sectionTitle: { fontSize: 16, fontWeight: "700", color: "rgba(255,215,0,0.5)", letterSpacing: 1, marginTop: 8 },
  recentItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: "#0f0f0f",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.2)",
    padding: 12,
  },
  recentText: { flex: 1 },
  recentName: { fontSize: 16, fontWeight: "700", color: GOLD },
  recentDetail: { fontSize: 13, color: "rgba(255,215,0,0.5)", marginTop: 2 },

  // Shared
  bigIcon: { fontSize: 80, textAlign: "center" },
  pageTitle: { fontSize: 32, fontWeight: "800", color: GOLD, marginTop: 8 },
  pageSubtitle: { fontSize: 17, color: "rgba(255,215,0,0.7)", textAlign: "center", marginTop: 10, lineHeight: 24 },
  primaryBtn: {
    marginTop: 28,
    backgroundColor: GOLD,
    paddingHorizontal: 48,
    paddingVertical: 16,
    borderRadius: 32,
    ...GOLD_GLOW,
  },
  primaryBtnText: { fontSize: 18, fontWeight: "700", color: "#000" },
  secondaryBtn: {
    marginTop: 12,
    backgroundColor: "rgba(255,215,0,0.12)",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.35)",
  },
  secondaryBtnDisabled: { opacity: 0.7 },
  secondaryBtnText: { fontSize: 15, fontWeight: "700", color: GOLD, textAlign: "center" },
  listingSpecList: { gap: 6, marginTop: 4 },
  listingSpecRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 },

  // Gold coin
  goldCoin: {
    backgroundColor: GOLD,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 16,
    borderWidth: 3,
    borderColor: "#FFF8DC",
  },
  goldCoinText: {
    fontWeight: "900",
    color: "#7A5C00",
  },

  // Auth
  authContainer: { flexGrow: 1, padding: 28, justifyContent: "center", gap: 24 },
  authLogoRow: { alignItems: "center", gap: 12 },
  authAppTitle: { fontSize: 32, fontWeight: "900", color: GOLD },
  authTabRow: { flexDirection: "row", backgroundColor: "#111", borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,215,0,0.2)", overflow: "hidden" },
  authTab: { flex: 1, paddingVertical: 12, alignItems: "center" },
  authTabActive: { backgroundColor: GOLD_DIM, ...GOLD_GLOW },
  authTabText: { fontSize: 15, fontWeight: "600", color: "rgba(255,215,0,0.4)" },
  authTabTextActive: { color: GOLD },
  authForm: { gap: 14 },
  input: {
    backgroundColor: "#111",
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.3)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: GOLD,
  },
  passwordField: { flexDirection: "row", alignItems: "center", backgroundColor: "#111", borderWidth: 1, borderColor: "rgba(255,215,0,0.3)", borderRadius: 12 },
  passwordInput: { flex: 1, minWidth: 0, borderWidth: 0, backgroundColor: "transparent" },
  passwordToggle: { minWidth: 64, minHeight: 48, paddingHorizontal: 12, alignItems: "center", justifyContent: "center" },
  passwordToggleText: { color: GOLD, fontSize: 14, fontWeight: "700" },
  authError: { fontSize: 14, color: "#FF4444", textAlign: "center" },
  authRecoverBtn: { backgroundColor: "rgba(255,215,0,0.1)", borderWidth: 1, borderColor: "rgba(255,215,0,0.3)", borderRadius: 10, padding: 12, alignItems: "center" },
  authRecoverText: { fontSize: 13, color: GOLD, fontWeight: "600", textAlign: "center" },
  guestBtn: { marginTop: 16, alignItems: "center", padding: 8 },
  guestBtnText: { fontSize: 14, color: "rgba(255,215,0,0.7)", fontWeight: "600", textDecorationLine: "underline" },
  guestBtnSubtext: { fontSize: 11, color: "rgba(255,215,0,0.35)", textAlign: "center", marginTop: 4, paddingHorizontal: 16 },

  // Account
  accountContainer: { padding: 24, gap: 16, paddingBottom: 40 },
  profileSection: { alignItems: "center", gap: 8, paddingVertical: 8 },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: GOLD_DIM,
    borderWidth: 2,
    borderColor: GOLD,
    alignItems: "center",
    justifyContent: "center",
    ...GOLD_GLOW,
  },
  avatarCircleLarge: { width: 90, height: 90, borderRadius: 45 },
  avatarInitials: { fontSize: 32, fontWeight: "800", color: GOLD },
  avatarText: { fontSize: 40 },
  profileName: { fontSize: 24, fontWeight: "800", color: GOLD },
  profileEmail: { fontSize: 14, color: "rgba(255,215,0,0.5)" },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  statBox: {
    flex: 1, minWidth: "45%", alignItems: "center",
    backgroundColor: "#0f0f0f", borderRadius: 16,
    borderWidth: 1, borderColor: "rgba(255,215,0,0.2)",
    padding: 14,
  },
  statBoxWide: { minWidth: "100%", flex: undefined, width: "100%" },
  statNumber: { fontSize: 28, fontWeight: "900", color: GOLD },
  statLabel: { fontSize: 11, color: "rgba(255,215,0,0.45)", textAlign: "center", marginTop: 4, letterSpacing: 0.5 },
  detailedStatsBtn: {
    backgroundColor: "#0f0f0f", borderWidth: 1, borderColor: "rgba(255,215,0,0.3)", borderRadius: 12,
    paddingVertical: 12, alignItems: "center", ...GOLD_GLOW,
  },
  detailedStatsBtnText: { fontSize: 14, fontWeight: "700", color: "rgba(255,215,0,0.7)" },
  statCoinRow: {
    flexDirection: "row", alignItems: "center", gap: 12,
    backgroundColor: "#0f0f0f", borderRadius: 14,
    borderWidth: 1, borderColor: "rgba(255,215,0,0.15)", padding: 12,
  },
  statCoinName: { fontSize: 15, fontWeight: "700", color: GOLD },
  statCoinSub: { fontSize: 12, color: "rgba(255,215,0,0.5)", marginTop: 2 },
  statCoinBadge: { backgroundColor: GOLD_DIM, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, borderColor: "rgba(255,215,0,0.3)" },
  statCoinBadgeText: { fontSize: 14, fontWeight: "800", color: GOLD },
  signOutBtn: {
    marginTop: 8, borderWidth: 1, borderColor: "rgba(255,215,0,0.3)",
    borderRadius: 32, paddingVertical: 14, alignItems: "center", ...GOLD_GLOW,
  },
  signOutText: { fontSize: 16, fontWeight: "700", color: "rgba(255,215,0,0.6)" },

  // Badges screen
  badgesScroll: { padding: 20, paddingBottom: 40 },
  badgesProgressRow: { marginBottom: 24 },
  badgesProgressText: { fontSize: 13, color: GOLD, fontWeight: "700", marginBottom: 8, textAlign: "center" },
  badgesProgressTrack: { height: 6, backgroundColor: "rgba(255,215,0,0.15)", borderRadius: 3, overflow: "hidden" },
  badgesProgressFill: { height: 6, backgroundColor: GOLD, borderRadius: 3 },
  badgesCatSection: { marginBottom: 28 },
  badgesCatTitle: { fontSize: 13, fontWeight: "900", color: GOLD, letterSpacing: 1.2, marginBottom: 12, textTransform: "uppercase" },
  badgesGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  badgeCard: {
    width: "47%", backgroundColor: "rgba(255,215,0,0.04)", borderRadius: 14,
    borderWidth: 1, borderColor: "rgba(255,215,0,0.12)",
    padding: 14, alignItems: "center",
  },
  badgeCardEarned: {
    backgroundColor: "rgba(255,215,0,0.09)", borderColor: GOLD,
    shadowColor: GOLD, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 8, elevation: 6,
  },
  badgeCardIcon: { fontSize: 34, marginBottom: 6 },
  badgeCardIconLocked: { opacity: 0.35 },
  badgeCardName: { fontSize: 13, fontWeight: "800", color: "#fff", textAlign: "center", marginBottom: 3 },
  badgeCardNameLocked: { color: "rgba(255,255,255,0.35)" },
  badgeCardDesc: { fontSize: 11, color: "rgba(255,255,255,0.45)", textAlign: "center", lineHeight: 15, marginBottom: 8 },
  badgeEarnedTag: { fontSize: 11, fontWeight: "800", color: GOLD },
  badgeLockedTag: { fontSize: 11, color: "rgba(255,255,255,0.25)" },

  // Role badges
  roleBadgeAdmin: { marginTop: 4, backgroundColor: "rgba(255,165,0,0.15)", borderRadius: 20, borderWidth: 1, borderColor: "rgba(255,165,0,0.5)", paddingHorizontal: 14, paddingVertical: 4 },
  roleBadgeMember: { marginTop: 4, backgroundColor: "rgba(255,215,0,0.08)", borderRadius: 20, borderWidth: 1, borderColor: "rgba(255,215,0,0.2)", paddingHorizontal: 14, paddingVertical: 4 },
  roleBadgeText: { fontSize: 12, fontWeight: "700", color: GOLD, letterSpacing: 0.5 },

  // Admin panel button on account screen
  lbCatRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  lbCatBtn: {
    width: "48%", paddingVertical: 9, alignItems: "center", borderRadius: 10,
    borderWidth: 1, borderColor: "rgba(255,215,0,0.2)", backgroundColor: "#0f0f0f",
  },
  lbCatBtnActive: { backgroundColor: GOLD_DIM, borderColor: GOLD, ...GOLD_GLOW },
  lbCatText: { fontSize: 11, fontWeight: "600", color: "rgba(255,215,0,0.4)", textAlign: "center" },
  lbCatTextActive: { color: GOLD },
  lbRow: {
    flexDirection: "row", alignItems: "center", gap: 12,
    backgroundColor: "#0f0f0f", borderRadius: 14,
    borderWidth: 1, borderColor: "rgba(255,215,0,0.15)", padding: 14,
  },
  lbRowMe: { borderColor: GOLD, backgroundColor: "rgba(255,215,0,0.06)", ...GOLD_GLOW },
  lbRank: { fontSize: 18, fontWeight: "800", color: GOLD, width: 36, textAlign: "center" },
  lbInfo: { flex: 1 },
  lbName: { fontSize: 15, fontWeight: "700", color: "rgba(255,215,0,0.8)" },
  lbNameMe: { color: GOLD },
  lbSub: { fontSize: 12, color: "rgba(255,215,0,0.45)", marginTop: 2 },
  lbBadge: { backgroundColor: "rgba(255,215,0,0.1)", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, borderColor: "rgba(255,215,0,0.25)" },
  lbBadgeGold: { backgroundColor: GOLD_DIM, borderColor: GOLD },
  lbBadgeText: { fontSize: 14, fontWeight: "800", color: "rgba(255,215,0,0.6)" },
  lbBadgeTextGold: { color: GOLD },
  lbRowFlash: { backgroundColor: "rgba(255,215,0,0.12)", borderColor: GOLD },
  lbLiveRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  lbLiveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#00e676", marginRight: 6 },
  lbLiveText: { fontSize: 11, fontWeight: "900", color: "#00e676", letterSpacing: 1.5 },
  lbUpdatedText: { fontSize: 11, color: "rgba(255,215,0,0.45)" },
  searchBar: {
    flexDirection: "row", alignItems: "center", gap: 10,
    backgroundColor: "#111", borderWidth: 1, borderColor: "rgba(255,215,0,0.25)",
    borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10,
    ...GOLD_GLOW,
  },
  searchIcon: { fontSize: 16 },
  searchInput: { flex: 1, fontSize: 15, color: GOLD },
  searchClear: { fontSize: 14, color: "rgba(255,215,0,0.4)", paddingLeft: 4 },
  searchEmpty: { fontSize: 14, color: "rgba(255,215,0,0.4)", textAlign: "center", marginTop: 8 },
  adminPanelGlow: {
    borderRadius: 16,
    backgroundColor: "#1a0f00",
    shadowColor: "#FFA500", shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.75, shadowRadius: 12, elevation: 10,
  },
  adminPanelBtn: {
    backgroundColor: "rgba(255,165,0,0.12)", borderRadius: 16,
    borderWidth: 1, borderColor: "rgba(255,165,0,0.5)",
    paddingVertical: 14, alignItems: "center",
  },
  adminPanelBtnText: { fontSize: 16, fontWeight: "700", color: "#FFA500" },

  // Auth extras
  inputAdmin: { borderColor: "rgba(255,165,0,0.5)" },
  adminCodeToggle: { fontSize: 13, color: "rgba(255,215,0,0.4)", textAlign: "center", textDecorationLine: "underline" },

  // Admin screen
  adminBadge: { alignSelf: "center", backgroundColor: "rgba(255,165,0,0.12)", borderRadius: 20, borderWidth: 1, borderColor: "rgba(255,165,0,0.5)", paddingHorizontal: 18, paddingVertical: 6 },
  adminBadgeText: { fontSize: 13, fontWeight: "700", color: "#FFA500", letterSpacing: 0.5 },
  adminUserCard: {
    backgroundColor: "#0f0f0f", borderRadius: 16,
    borderWidth: 1, borderColor: "rgba(255,215,0,0.2)",
    padding: 14, gap: 8,
  },
  adminUserHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  adminUserAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: GOLD_DIM, borderWidth: 1, borderColor: GOLD, alignItems: "center", justifyContent: "center" },
  adminUserAvatarText: { fontSize: 18, fontWeight: "800", color: GOLD },
  adminUserName: { fontSize: 16, fontWeight: "700", color: GOLD },
  adminUserCount: { fontSize: 12, color: "rgba(255,215,0,0.5)", marginTop: 2 },
  adminScanRow: { flexDirection: "row", justifyContent: "space-between", paddingLeft: 4 },
  adminScanCoin: { fontSize: 13, color: "rgba(255,215,0,0.7)", flex: 1 },
  adminScanTime: { fontSize: 12, color: "rgba(255,215,0,0.4)" },
  adminMore: { fontSize: 12, color: "rgba(255,215,0,0.35)", paddingLeft: 4 },
});

export default styles;
